version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_DB=$DB_DB
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - .:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    command: [ "tail", "-f", "/dev/null" ]
    ports:
      - 8080:8080
    volumes:
      - .:/app
