-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Persona"
(
    id_per serial NOT NULL,
    nombre text NOT NULL,
    documento text NOT NULL,
    celular text,
    edad smallint NOT NULL,
    sexo text NOT NULL,
    residencia serial NOT NULL,
    PRIMARY KEY (id_per),
    CONSTRAINT unique_documento UNIQUE (documento)
);

CREATE TABLE IF NOT EXISTS public."Municipio"
(
    id serial NOT NULL,
    nombre text NOT NULL,
    area integer NOT NULL,
    altitud integer NOT NULL,
    governador serial NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT unique_governador UNIQUE (governador)
);

CREATE TABLE IF NOT EXISTS public."Vivienda"
(
    id_viv serial NOT NULL,
    direction text NOT NULL,
    capacidad integer NOT NULL,
    niveles integer NOT NULL,
    municipio serial NOT NULL,
    PRIMARY KEY (id_viv)
);

CREATE TABLE IF NOT EXISTS public."Vivienda_Persona"
(
    "Vivienda_id_viv" serial NOT NULL,
    "Persona_id_per" serial NOT NULL
);

ALTER TABLE IF EXISTS public."Persona"
    ADD CONSTRAINT fk_reside_en FOREIGN KEY (residencia)
    REFERENCES public."Vivienda" (id_viv) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Municipio"
    ADD CONSTRAINT fk_gobernado_por FOREIGN KEY (governador)
    REFERENCES public."Persona" (id_per) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vivienda"
    ADD FOREIGN KEY (municipio)
    REFERENCES public."Municipio" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vivienda_Persona"
    ADD CONSTRAINT fk_vivienda FOREIGN KEY ("Vivienda_id_viv")
    REFERENCES public."Vivienda" (id_viv) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vivienda_Persona"
    ADD CONSTRAINT fk_propietario FOREIGN KEY ("Persona_id_per")
    REFERENCES public."Persona" (id_per) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;